# Generated by Django 5.2.2 on 2025-06-09 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название устройства')),
                ('model', models.CharField(max_length=255, verbose_name='Модель устройства')),
                ('ip', models.CharField(max_length=255, verbose_name='IP адрес устройства')),
                ('login', models.CharField(max_length=255, verbose_name='Логин устройства')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль устройства')),
                ('description', models.CharField(max_length=255, verbose_name='Описание устройства')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.devicetype', verbose_name='Тип устройства')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='service.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
    ]
